# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit, push]
default_language_version:
    python: python3
exclude: "dat"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-builtin-literals
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: detect-private-key
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit # security vulnerabilities
        args: [ "--exclude", "setup.py,bin,tests" ]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy # type annotations
        exclude: ^examples/,^wip/,^tests/
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.2
    hooks:
    -   id: pylint
        exclude: ^wip/,^tests/
        files: ^kglab/
-   repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
    -   id: codespell # spell-check source code
        args: ["-L", "wit,fils,basf"] # comma separated list of words to ignore.
        exclude: ^examples\/|.*\.ipynb
        language: python
        types: [text]
