{% set name = "kglab" %}
{% set version = "0.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kglab-{{ version }}.tar.gz
  sha256: 12624e4cc5276aa043a752e731cf1074f4c4863ba171de9a03e3024c1602b6d8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - chocolate >=0.0.2
    - csvwlib >=0.3.2
    - decorator >=4.4.2
    - fsspec >=0.8.5
    - gcsfs >=0.7.1
    - gensim >=3.8.3
    - icecream >=2.0
    - matplotlib-base >=3.3.4
    - networkx >=2.6
    - numpy >=1.19.4
    - owlrl >=6.0.2
    - pandas >=1.1.5
    - pslpython >=2.2.2
    - pyarrow >=2.0.0
    - pygments >=2.7.4
    - pylev >=1.3
    - pynvml >=8.0.4
    - pyshacl >=0.17.3
    - python >=3.6
    - python-dateutil >=2.8
    - pyvis >=0.1.7.0
    - rdflib >=6.0.2
    - requests >=2.25.1
    - scikit-learn >=0.20.2
    - statsmodels >=0.12
    - torch >=1.8
    - tqdm >=4.56
    - urlpath >=1.1.7

test:
  imports:
    - kglab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://derwen.ai/docs/kgl/
  summary: A simple abstraction layer in Python for building knowledge graphs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ceteri
