site_name: kglab
site_description: Graph-Based Data Science
site_url: https://github.com/DerwenAI/kglab
site_author: kglab contributors, with Derwen, Inc.

repo_url: https://github.com/DerwenAI/kglab
repo_name: DerwenAI/kglab

copyright: Source code and documentation are <strong><a href="https://github.com/DerwenAI/kglab/blob/main/LICENSE" target="_blank">licensed</a></strong> under an MIT License; Copyright &copy; 2020-2022 <strong><a href="https://derwen.ai/" target="_blank">Derwen, Inc.</a></strong>

nav:
    - Home: index.md

    - Start:
        - Overview: overview.md
        - A Grammar of Learning: learn.md
        - Getting Started: start.md

    - Tutorial:
        - Syllabus: tutorial.md
        - Construction:
            - Data and Ontology sources: ex0_0.md
            - Build an RDF graph using `RDFlib`: ex1_0.md
            - Leverage the `kglab` abstraction layer: ex1_1.md
            - Build a medium size KG from a CSV dataset: ex2_0.md
            - Using `morph-kgc` to input from relational databases, CSV, etc: ex2_1.md
        - Querying:
            - Run SPARQL queries: ex4_0.md
        - Validation:
            - SHACL validation with `pySHACL`: ex5_0.md
        - Visualization:
            - Interactive graph visualization with `PyVis`: ex3_0.md
        - Graph Algorithms:
            - Graph algorithms with `NetworkX`: ex6_0.md
            - Discover community structure using `iGraph` and `leidenalg`: ex6_1.md
        - Inference:
            - Measurement and inference: ex7_0.md
            - Statistical relational learning with `pslpython`: ex7_1.md
        - Embedding:
            - Vector embedding with `gensim`: ex8_0.md

    - Concepts:
        - What's a Knowledge Graph?: what.md
        - Graph Concepts: concepts.md
        - Inference capabilities: infer.md

    - Evidence:
        - Use Cases: use_case.md

    - Technical Reference:
        - Package Reference: ref.md
        - Dependencies: depend.md
        - Build Instructions: build.md

    - Community:
        - Community Resources: community.md
        - Acknowledgements: ack.md

    - Research Guides:
        - Glossary: glossary.md
        - Bibliography: biblio.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.png
  logo: assets/logo.png
  features:
    - navigation.instant

plugins:
  - mknotebooks
  - git-revision-date

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

use_directory_urls: true

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - toc:
      toc_depth: 3
      permalink: true
